local damage = workspace.__THINGS.__REMOTES.giant_dealdamage

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

damage:FireServer(unpack(um))
damage:FireServer(unpack(dois))
damage:FireServer(unpack(tres))
damage:FireServer(unpack(quatro))
damage:FireServer(unpack(cinco))
damage:FireServer(unpack(seis))
damage:FireServer(unpack(sete))
damage:FireServer(unpack(oito))
damage:FireServer(unpack(nove))

